# Generated by Django 4.2.5 on 2024-02-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='profession',
            field=models.TextField(choices=[('director', 'director'), ('actor', 'actor'), ('producer', 'producer')], null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(null=True, verbose_name='role'),
        ),
    ]
